=begin
#Dkron REST API

#You can communicate with Dkron using a RESTful JSON API over HTTP. Dkron nodes usually listen on port `8080` for API requests. All examples in this section assume that you've found a running leader at `localhost:8080`.  Dkron implements a RESTful JSON API over HTTP to communicate with software clients. Dkron listens in port `8080` by default. All examples in this section assume that you're using the default port.  Default API responses are unformatted JSON add the `pretty=true` param to format the response. 

OpenAPI spec version: 2.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

# Common files
require 'dkron-ruby/api_client'
require 'dkron-ruby/api_error'
require 'dkron-ruby/version'
require 'dkron-ruby/configuration'

# Models
require 'dkron-ruby/models/execution'
require 'dkron-ruby/models/job'
require 'dkron-ruby/models/member'
require 'dkron-ruby/models/processors'
require 'dkron-ruby/models/status'

# APIs
require 'dkron-ruby/api/default_api'
require 'dkron-ruby/api/executions_api'
require 'dkron-ruby/api/jobs_api'
require 'dkron-ruby/api/members_api'

module Dkron
  class << self
    # Customize default settings for the SDK using block.
    #   Dkron.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
